on:
  - push
  - pull_request

name: test

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - 'chap_01_money'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        working-directory: ${{ matrix.dir }}
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo test
        working-directory: ${{ matrix.dir }}
        uses: actions-rs/cargo@v1
        with:
          command: test
